### ISSUE TITLE
Linkportals not working

### ISSUE THREAD

**Issue by DarkyG2** [Folia-Inquisitors/MoreFoWorld#1]
when trying to link my ressource_world with my ressource_world_nether it will always teleport me to the world_nether and world.

Config: 
```YAML
nether:
  ressource_world: ressource_world_nether
  ressource_world_nether: ressource_world
end:
  ressource_world: ressource_world_the_end
  ressource_world_the_end: ressource_world
```

```YAML
# The settings for each world
worlds:
  ressource_world:
    seed: 0
    biome-provider: ''
    generator-settings: ''
    hardcore: false
    type: NORMAL
    generate-structures: true
    generator: ''
    environment: NORMAL
  ressource_world_nether:
    seed: 0
    biome-provider: ''
    generator-settings: ''
    hardcore: false
    type: NORMAL
    generate-structures: true
    generator: ''
    environment: NETHER   
  ressource_world_the_end:
    seed: 0
    biome-provider: ''
    generator-settings: ''
    hardcore: false
    type: NORMAL
    generate-structures: true
    generator: ''
    environment: THE_END 

  claim_world:
    seed: 0
    biome-provider: ''
    generator-settings: ''
    hardcore: false
    type: NORMAL
    generate-structures: true
    generator: ''
    environment: NORMAL
  claim_world_nether:
    seed: 0
    biome-provider: ''
    generator-settings: ''
    hardcore: false
    type: NORMAL
    generate-structures: true
    generator: ''
    environment: NETHER   
  claim_world_the_end:
    seed: 0
    biome-provider: ''
    generator-settings: ''
    hardcore: false
    type: NORMAL
    generate-structures: true
    generator: ''
    environment: THE_END 

debug: false

```
